### ISSUE TITLE
attempt to lint yaml for users upon error

### ISSUE THREAD

**Issue by LincolnBryant** [slateci/slate-client-server#104]
Brian Lin suggested to me that we have the SLATE server (or client, I suppose) try to lint the values.yaml coming from a user. It's easy to make a mistake and produce malformed yaml. Would be nice to try to lint the yaml for the user and give them a hint as to where they've gone wrong.

**Comment by Mansalu** [comment]
@jmcragun and I looked at this today and we now believe this issue is a concern of the server. The server not the client possesses the yaml-cpp library we use for parsing. The values/yaml related errors come from the server response, and we'd want to be able to propagate the helpful new error handling to portal requests as well.

I think the key thing here is the user experience of submitting an accidentally malformed values file and receiving an unhelpful error from SLATE. In what ways can a file be malformed?
-Spacing issues
-Field missing from file
-Extra field in file
-Unexpected file structure (ie correct values and syntax not in correct hierarchy)
-Type problems
-Others?

How do we detect these different scenarios in code? What is the most helpful way to let the user know the issue with their file? We probably want to take some time to understand how these happen in the first place as well:
-Typos and bad copy paste
-Using old values after chart update
-Poor documentation (on the type or expected input of a values field)
-Others?

Example: I can try to install a Chart today using a Values file that is valid yaml with all the expected fields but incorrect hierarchy. Unhelpfully, the error I get from SLATE is `Failed to install application instance: Configuration could not be parsed as YAML `

**Comment by Mansalu** [comment]
@jmcragun 
Possible next steps: 
-Research and understand the tools available in the yaml-cpp library (can we use linting?)
-Determine in code what way(s) the values yaml was malformed and propagate that as an error in the response
-ApplicationCommands.cpp:238-258 seems like the best place to start improvements in code

**Comment by cnweaver** [comment]
Detecting malformed data is already done, using `extractInstanceTag` from ApplicationCommands.cpp:256-257. If you want a diagnosis of why the YAML is malformed about your only option is to capture the contents (`.what()`) of the `YAML::ParserException` caught inside the function. Whether that will be at all useful to the user is something I've never checked.

**Comment by Mansalu** [comment]
Ok thanks for the insight here, Chris. Can we detect at all between YAML that is malformed for what's expected and YAML that just is not syntactically valid?

**Comment by cnweaver** [comment]
Syntactic invalidity is the only sense of malformed-ness which can be automatically detected; there's no way for a YAML parser to know about the semantics of a particular chart's values file (and that I can think of helm itself imposes no general semantic on values files). However, some of the charts do enforce their own semantic constraints on their input.

**Comment by jmcragun** [comment]
Would it be feasible to write our own linting code to validate the semantics of the value files in the catalog alongside the parser to check the syntax? What kind of structural complexity are we looking at here?

**Comment by cnweaver** [comment]
The semantics are specific to each chart, so this should really be evaluated at the helm level as a part of the chart. See for example https://github.com/slateci/slate-catalog/blob/537fd4545f9697e1ed280be4cdaf86f845cf5eb9/incubator/jupyter-notebook/jupyter-notebook/templates/requirements.yaml .

**Comment by Mansalu** [comment]
Could we create a schematic to compare against like we do with the JSON responses/requests?

This would of course involve maintaining a new piece for each chart values...
