### ISSUE TITLE
Restart instance echos 'temporarily unavailable' html page

### ISSUE THREAD

**Issue by bbockelm** [slateci/slate-client-server#106]
When I did a `slate instance restart ...`, after awhile I got this:

```
Failed to restart instance instance_XVjcgHWzCfU: <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/x
html11.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
    <head>
        <title>The page is temporarily unavailable</title>
```

(and gobs of HTML follow).

I suspect there's an HTTP status code that should be retried here instead of echoing out the page contents.

**Comment by cnweaver** [comment]
This is not, I think, really a bug in the client, and it's difficult to come up with a simple thing it could do differently to avoid it. If I'm understanding correctly, and the endpoint being connected to is on port 443 rather than 18080, this is nginx generating an error page because it failed to pass the request through to the actual SLATE API (or more likely failed to get a result back soon enough). Unfortunately, when doing so it doesn't really adhere to the API (not knowing or caring what it is), and generates a whole ugly webpage where a short text string is expected. (You almost certainly don't want to retry, because then your pods will likely get restarted again for no good reason.)

I would interpret this more as an nginx configuration problem: It should perhaps have a lighter-weight error page that it serves in such situation, more suitable for consumption by the SLATE client, and if the error page was shown because it timed out while the SLATE API was working, it should perhaps have its timeout adjusted. There are of course deeper architectural issues with operations which take too long and make the SLATE server take too long to handle requests. That could perhaps be addressed by running all operations on a background thread, and if they take too long returning a result to the user which amounts to 'sorry, it's not done yet, but I think it's working so far'.  Actually cancelling the worker thread on the server might be rather difficult.

**Comment by bbockelm** [comment]
For what it's worth - after the error, I manually retried after a few seconds and it came back just fine.  What about just having the client do a retry on HTTP status 503?

Another thought is to send a chunked response (https://en.wikipedia.org/wiki/Chunked_transfer_encoding) immediately from the API; this allows streaming updates from the API that can give the client status updates.

**Comment by cnweaver** [comment]
As mentioned above, retrying will probably repeat the operation, which may have significant consequences (counting towards LE certificate limits comes to mind). An error 503 isn't an allowed part of the SLATE API; it's a spurious error being injected by nginx. The API could be extended to allow it, but this would both have to confront the fact that retrying isn't necessarily the right reaction, and that would ignore the real problem, which is one part of the system being slow (the requested operation) and another impatient (nginx). 

Chunked responses would be nice, but are not supported in the REST framework used to implement the API. 

One other solution for this would be to act more like the Kubernetes API, and be more asynchronous, returning success as soon as an operation has begun, or gotten off to a reasonable start. This is, however, quite annoying for the user, who has to deal with polling until the operation actually completes (if waiting for completion is desired, but it usually is). It also causes issues about where to store errors if they come up, leading to things like Kubernete's awful 'events' mechanism.

**Comment by bbockelm** [comment]
> As mentioned above, retrying will probably repeat the operation

Ah, that part I missed - I thought this was a simple `GET` (or other idempotent op).

> Chunked responses would be nice, but are not supported in the REST framework used to implement the API.

Ah, shoot!

> One other solution for this would be to act more like the Kubernetes API, and be more asynchronous, returning success as soon as an operation has begun, or gotten off to a reasonable start.

That does sound like a way forward - but potentially a big refactor from what you describe above?  Would it be better to simply give a quicker application-level timeout before the nginx one is hit?  If we give a unique instance start time in the timeout, the client could query to see if it's the same instance version running.

**Comment by cnweaver** [comment]
'Being more asynchronous' could be done fairly easily if one made no effort to report errors; just move whatever code is in the synchronous path into a separate thread, `detach()` it, and hope for the best. Reporting errors usefully would definitely require substantial redesign work in such a scheme. 

As far as timing out goes, it boils down to something similar, depending on the level at which it is done. If the client timed out and stopped waiting for the server to respond, it would be necessary to do something like what you suggest to give the user a way to figure out whether the restart actually happened, is still happening, if it failed (same error reporting issue as in 'be more asynchronous'). So this would provide something of an implementation shortcut, but it incurs most of the same drawbacks. 

The Kubernetes API itself generally takes the 'be more asynchronous' route, and having been designed for this it both has an error reporting mechanism and is able to represent intermediate states for operations which are in-progress but not done. After the amount of time spent trying to reliably get it to do anything which consists of chained operations, in my opinion the burden this places on the user is substantial (polling to see if every operation is done yet is not fun, and easy to mess up), and the error reporting mechanism is frequently of very little help (Waited too long to query for error messages? Too bad, they're gone forever.). It might be worthwhile to evolve in this direction, but it would take a good deal of careful thought.

**Comment by jstidd** [comment]
We've updated the timeout in nginx. Hopefully this will help with the error.

**Comment by sthapa** [comment]
Closing since this is related to the previous nginx/slate api server infrastructure and not the gke env slate runs in
