### ISSUE TITLE
Improve cluster force deletion

### ISSUE THREAD

**Issue by Mansalu** [slateci/slate-client-server#140]
SLATE should attempt to detect if a cluster is reachable. If a cluster is not-reachable, and a force deletion is requested, SLATE should perform the deletion without waiting for timeouts. The relevant section of code is `src/ClusterCommands.cpp:L720`.

Reachability is already stored by SLATE in the cluster status.

**Comment by LincolnBryant** [comment]
My impression was that SLATE was going to make every effort to contact the cluster before giving up and deleting it. If a cluster couldn't be reached due to an ephemeral error when a deletion was requested, it would leave objects in an orphaned state on the cluster.

**Comment by cnweaver** [comment]
Right, the cached reachability information was mostly for user convenience, and while a cluster that was unreachable 15 minutes ago probably still isn't, this may not always be true (and one reachable 15 minutes ago may not still be reachable). However, it might make sense to consolidate this into one check at the start of the cluster deletion process when `--force` has already been used? Otherwise, I think it tries to delete all instances and secrets, and will end up waiting for each of those requests to time out. If the whole cluster appears to really just be down, and the user has requested a force delete, it might make sense to jump striaght to the forcing part of those operations.

**Comment by sthapa** [comment]
Already implemented in part, don't have effort for further improvements
