### ISSUE TITLE
`test-group-deletion` and `test-cluster-deletion` timeout before result

### ISSUE THREAD

**Issue by ike091** [slateci/slate-client-server#148]
These two tests (15 and 21, respectively) timeout before they are able to return results. Both of them timeout for the same reason. They call the `kubernetes::kubectl` method, which in both cases attempts to run `kubectl --request-timeout=10s --kubeconfig=./kubeconfig.yaml get namespaces`. When this command is run manually, it succeeds almost instantly. However, inside the tests, the process running it never gets marked as `done` (specifically, it gets stuck in a loop inside of `Process.cpp` on line 593).

**Comment by cnweaver** [comment]
Is the child process actually completing? I.e. is this a bug in the subprocess code, or is it just the Kubernetes API responding slowly? Also, what does it mean for the tests to timeout? I don't remember any time limit being set in `ctest`.

**Comment by ike091** [comment]
I don't think the child process ever completes because it never is assigned an exit status. It gets stuck waiting for `!child.done()`. Timeout probably wasn't the best word, what happens is that the tests hang and never complete (20+ minutes without any new output).

**Comment by cnweaver** [comment]
Okay, hanging inefinitely was indeed what I would have expected. To narrow down what's going on, I think you want to check whether the child process really did exit; while the test is stuck use `ps` or similar to determine if there is still a kubectl process or not.

**Comment by ike091** [comment]
Ah gotcha. Looks like there is a `kubectl` process stuck in a zombie state (`ps` marks it as `<defunct>`).

**Comment by cnweaver** [comment]
Unfortunately, that seems to indicate a bug in the API server's child process handling, as it should reap that. I'll try to reprocude this and see if I can figure out what's gone wrong.

**Comment by jmcragun** [comment]
So I've been doing a bit of messing around with the tests and one thing I tried was to remove all of the prior steps of the tests (Note: specifically the tests where hanging occurs are those involving cascading deletion) such that all that happens is the initialization of a `TestContext`, in which the test context is used in order to save the kube config, and then the kubectl command is ran like normal along with the rest of the test., using the aforementioned config. (What the rest of the test does is simply parse the output of the kubectl call to see if the created namespace is no longer present) 

We would actually expect this test to pass since the final assertion would now be checking for the absence of a group that is never created in the first place. However, instead the test crashes with the following error message:

```
ProcessHandle startProcessAsync(std::string, const std::vector<std::basic_string<char> >&, const std::map<std::basic_string<char>, std::basic_string<char> >&, ForkCallbacks&&, bool): Assertion `!reaperStop.load() && "Process reaper must be running"' failed.
```

Could this be related to the original problem? If I'm understanding this output correctly (and if not please explain!) then this suggests to me that the reason we're hanging is that the process reaper is not running in the first place. If that is correct, then does anyone have any idea why that might be happening?

**Comment by cnweaver** [comment]
It seems unlikely that this was the original issue; if you didn't see this message before, then something else was probably causing it to break/hang before it hit this problem. You need to call `startReaper()` from `Process.h` if you want to run child processes, like `kubectl`.
