### ISSUE TITLE
Save original values file passed in as a string in SLATE/Dynamo

### ISSUE THREAD

**Issue by jstidd** [slateci/slate-client-server#152]
Github actions should be able to compare the current values file in github with the values file saved in SLATE. There is currently a way to get the values from SLATE, but it is formatted differently. 

Possibly just BASE64 encode the string and save in dynamodb. 

----
If getting values file from SLATE api bogs it down, we could create a Go app to pull the values file from dynamo so that github actions can compare rather to update SLATE or not.

**Comment by cnweaver** [comment]
Another option, if you're making a request to the SLATE API anyway, would be to send it the new file and ask it to normalize it in the same way as the existing data (i.e. run `reduceYAML` on it) and determine whether there are any changes. (This would require a new API function to do this, but it would be a simple one to add.) Storing two copies of the data in Dynamo seems wasteful, and IIRC part of the reason that SLATE alters files is to throw away comments in order to reduce the size of the data which must be stored and reduce the chances of hitting Dynamo's record size limit. (A quick check suggests that ~65% of the data in default values files in the catalog is comments which are currently discarded.) An extra layer of Base64 encoding would instead increase the data size by 33%, which would make hitting the size limit more likely.

**Comment by Mansalu** [comment]
I'm going to agree with Chris, I think it would be good to avoid hacking around this. I was never fully up to speed on the reason for running reduceYAML, but my preference would probably be to stop minimizing the values. This would also help the output of `slate instance info --conf`

**Comment by Mansalu** [comment]
To follow up a bit more, does GHA really need to compare values directly itself? That seems like a bit of an antipattern. I think it might be preferable to have SLATE offer this comparison itself through the standard interface. We could build something sort of similar to like a `terraform plan` for SLATE. Perhaps as a flag to the existing `slate instance update`...maybe `slate instance update --plan`, where you present a values file for an instance and SLATE determines how the instance would change, if at all.

**Comment by robrwg** [comment]
Jason - can you drop a note in here why this is being closed?
