### ISSUE TITLE
`slate volume list` returns curl error 

### ISSUE THREAD

**Issue by SkoUtes** [slateci/slate-client-server#154]
When making a request for `slate volume list` the api-dev server will crash and return a curl (52) error. `src/Client.cpp:L3079`
```
slate: Exception: curl perform GET failed curl error:
NSS: client certificate not found (nickname not specified)
```
The same output is generated from `slate instance delete`. Could be related to recent changes to the API, only occurs when using the api-dev endpoint.

@jstidd

**Comment by cnweaver** [comment]
The volume problem is here: https://github.com/slateci/slate-client-server/blob/master/src/VolumeClaimCommands.cpp#L91

THis attempts to extract data from the JSON object regardless of whether it was successfully populated (line 85 may have instead thrown an exception), or has the right structure. It should be guarded by a check that at least:

	volumeStatus.IsObject() && volumeStatus.HasMember("status")
           && volumeStatus["status"].IsObject() && volumeStatus["status"].HasMember("phase")

If that check does not pass, a fixed, alternate value (e.g. `"unknown"`) should probably be set for the status field. 

The crash is showing up on the dev API server because it has records of volumes which are on defunct clusters (which trigger the error messages on lines 78 and 85, but the current code proceeds anyway).
