### ISSUE TITLE
Quote namespace names

### ISSUE THREAD

**Issue by LincolnBryant** [slateci/slate-client-server#166]
When installing a cluster today, I ran into the following strange issue after a typo:
```
SLATE namespace. The default is 'slate-system': y
Creating Cluster 'y'...
slate: Exception: Cluster creation failed: error: unable to decode ".cluster.yaml.XXcbKCfm": resource.metadataOnlyObject.ObjectMeta: v1.ObjectMeta.Name: ReadString: expects " or n, but found t, error found in #10 byte of ...|:{"name":true}}|..., bigger context ...|io/v1alpha1","kind":"Cluster","metadata":{"name":true}}|...
```

It seems that SLATE did not like my namespace of 'y'. @cnweaver suggests this may be due to YAML type detection, and further suggests quoting the namespace name here:
https://github.com/slateci/slate-client-server/blob/master/src/client/ClusterRegistration.cpp#L362

**Comment by adityavisv** [comment]
Quoting the namespace at [this line in ClusterRegistration.cpp](https://github.com/slateci/slate-client-server/blob/master/src/client/ClusterRegistration.cpp#L362) fixes the issue while installing a cluster. Seems like the issue was yaml trying to interpret y (without quotes) as a bool type. See [YAML v1.1](https://yaml.org/type/bool.html) for more.

However, the [k8s documentation](https://kubernetes.io/docs/tasks/administer-cluster/namespaces/#creating-a-new-namespace) on creating a new namespace has a few rules on what counts as a valid namespace name. Apparently, namespace names are required to follow [RFC 1035](https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#rfc-1035-label-names), which means the name must:
* contain at most 63 characters
* contain only lowercase alphanumeric characters or '-'
* start with an alphabetic character
* end with an alphanumeric character

Do we want to enforce these conditions on a user-supplied namespace in the slate client, before invoking the kubectl command?

**Comment by adityavisv** [comment]
Opened https://github.com/slateci/slate-client-server/issues/170 to deal with the namespace name validation.

PR for this particular issue (quoting namespace) is open now.
