### ISSUE TITLE
Rename clusters

### ISSUE THREAD

**Issue by jstidd** [slateci/slate-client-server#246]
Will it be possible to rename clusters? It is a feature we would like, but if the cluster name is used as a key in Dynamodb, it would not be possible to rename unless the records are removed and re-entered in dynamo. 

If it is not the dynamodb key, please add a feature to rename the cluster.

**Comment by cnweaver** [comment]
If I remember correctly, inside the persistent store, references should be normalized to the IDs, and lookups are just allowed by name (which is converted to the ID automatically). Since at one time IDs and names were used somewhat more sloppily, some auditing would be required to make sure that I did normalize to IDs on all input paths. The other issue is that since a cluster's DNS name is provided to application instances started on it, changing the cluster name (and presumably replacing the DNS record) could break running user applications, and it seems there would be no foolproof way to automatically determine whether this would happen (or do anything about it).

**Comment by sthapa** [comment]
Closing since this is in the backlog and we don't have the effort to address this given the potential issues that Chris mentioned.
